name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *" # tiap 10 menit

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
          check-latest: true

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml python-dotenv

      - name: Run scheduled task
        run: python main.py

      - name: Upload rate logs
        uses: actions/upload-artifact@v4
        with:
          name: rate-logs
          path: data/rates/
