name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # tiap 10 menit

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
    #   - name: Install en_US.UTF-8 locale
    #     run: |
    #         sudo apt-get update
    #         sudo apt-get install -y locales
    #         sudo locale-gen en_US.UTF-8
    #         sudo update-locale LANG=en_US.UTF-8
    #     shell: bash
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml python-dotenv

      - name: Run scheduled task
        run: python main.py
